import os
import logging
from datetime import datetime
from typing import List
from .models import ResearchInsight

logger = logging.getLogger(__name__)


def synthesize_report(query: str, insights: List[ResearchInsight]) -> str:
    """
    Synthesizes discrete insights into a cohesive markdown report.
    Includes visual evidence (screenshots), source credibility assessment,
    cross-validation markers, and citations.
    """
    logger.info("🧠 Synthesizing final report...")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"# Deep Research Report: {query}\n\n"
    report += f"**Date:** {timestamp}\n"
    report += f"**Sources Analyzed:** {len(insights)}\n"
    report += f"**Generated by:** Deep Research Agent v3.0 (Production-Grade)\n\n"
    
    # --- Source Credibility Scoring ---
    credibility_tiers = {
        "nih.gov": "🏛️ Government", "cdc.gov": "🏛️ Government",
        "who.int": "🏛️ Government", "fda.gov": "🏛️ Government",
        "pubmed.ncbi.nlm.nih.gov": "🏛️ Government",
        "medlineplus.gov": "🏛️ Government",
        "mayoclinic.org": "🏥 Academic Medical Center",
        "clevelandclinic.org": "🏥 Academic Medical Center",
        "hopkinsmedicine.org": "🏥 Academic Medical Center",
        "heart.org": "🏥 Professional Organization",
        "drugs.com": "📖 Medical Reference",
        "webmd.com": "📖 Medical Reference",
        "healthline.com": "📖 Medical Reference",
    }
    
    # Categorize insights by source tier
    tiered_insights = {"🏛️ Government": [], "🏥 Academic Medical Center": [], 
                       "🏥 Professional Organization": [], "📖 Medical Reference": [], "📋 Other": []}
    for insight in insights:
        domain = insight.source_url.split("//")[-1].split("/")[0].replace("www.", "")
        tier = "📋 Other"
        for d, t in credibility_tiers.items():
            if d in domain:
                tier = t
                break
        tiered_insights[tier].append(insight)
    
    report += "## 1. Executive Summary\n"
    if insights:
        # Use top 3 most credible insights for summary
        combined_summary = " ".join([i.summary for i in insights[:3]])
        report += f"{combined_summary[:600]}...\n\n"
    else:
        report += "No insights available.\n\n"
    
    # Source credibility overview
    report += "## 2. Source Quality Assessment\n"
    report += "| Tier | Count | Sources |\n"
    report += "|------|-------|---------|\n"
    for tier, tier_insights in tiered_insights.items():
        if tier_insights:
            domains = set(i.source_url.split("//")[-1].split("/")[0].replace("www.", "") for i in tier_insights)
            report += f"| {tier} | {len(tier_insights)} | {', '.join(list(domains)[:3])} |\n"
    report += "\n"
    
    report += "## 3. Key Technical Findings\n"
    all_findings = []
    for insight in insights:
        for finding in insight.key_findings:
            all_findings.append(f"- {finding}")
    
    unique_findings = list(set(all_findings))
    report += "\n".join(unique_findings) + "\n\n"
    
    # Cross-validation section
    if len(insights) >= 2:
        report += "## 4. Cross-Validation\n"
        # Find corroborated findings
        finding_counts = {}
        for insight in insights:
            for finding in insight.key_findings:
                normalized = finding.lower().strip()
                key_words = frozenset(normalized.split()[:8])  # First 8 words as key
                if key_words not in finding_counts:
                    finding_counts[key_words] = {"finding": finding, "sources": []}
                finding_counts[key_words]["sources"].append(
                    insight.source_url.split("//")[-1].split("/")[0].replace("www.", "")
                )
        
        corroborated = {k: v for k, v in finding_counts.items() if len(v["sources"]) > 1}
        if corroborated:
            report += "**Findings confirmed by multiple sources:**\n"
            for _, data in list(corroborated.items())[:5]:
                report += f"- ✅ {data['finding']} *(Sources: {', '.join(set(data['sources']))})*\n"
        else:
            report += "No findings were confirmed by multiple independent sources.\n"
        report += "\n"
    
    report += "## 5. Detailed Analysis & Evidence\n"
    for i, insight in enumerate(insights, 1):
        report += f"### Source {i}: {insight.title}\n"
        report += f"**URL:** [{insight.source_url}]({insight.source_url})\n\n"
        report += f"**Summary:** {insight.summary}\n\n"
        
        # Include screenshot if available
        if insight.screenshot_path and os.path.exists(insight.screenshot_path):
            report += f"**Visual Evidence:**\n"
            # Use relative path for markdown if possible, or absolute
            # For local viewing, absolute or relative to report file works.
            # Assuming report is in output_dir, and screenshots in output_dir/screenshots
            rel_path = os.path.relpath(insight.screenshot_path, os.path.dirname(insight.screenshot_path) + "/..")
            report += f"![Screenshot]({rel_path})\n\n"
        
        if insight.relevant_quotes:
            report += "**Relevant Quotes:**\n"
            for quote in insight.relevant_quotes:
                report += f"> \"{quote}\"\n"
            report += "\n"
        
        # Include source links for depth-2 exploration
        if insight.source_links:
            report += "**Related Sources Found on Page:**\n"
            for link in insight.source_links[:3]:
                if link.startswith('http'):
                    report += f"- [{link[:60]}...]({link})\n"
            report += "\n"
        
        report += "\n---\n\n"
    
    report += "## 6. References & Citations\n"
    report += "| # | Source | Tier | URL |\n"
    report += "|---|--------|------|-----|\n"
    for i, insight in enumerate(insights, 1):
        domain = insight.source_url.split("//")[-1].split("/")[0].replace("www.", "")
        tier = "📋 Other"
        for d, t in credibility_tiers.items():
            if d in domain:
                tier = t
                break
        report += f"| {i} | {insight.title[:50]} | {tier} | [{insight.source_url[:40]}...]({insight.source_url}) |\n"
    
    report += "\n---\n\n"
    report += "*Generated by Deep Research Agent v3.0 - Source-Validated Web Intelligence System*\n"
    
    return report
